name: 'Build'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: 'Download Source'
        uses: actions/checkout@v3
        with:
          token: ${{ github.TOKEN }}

      - name: Checkout DevOps Capabilities Repo
        uses: actions/checkout@v3
        with:
          repository: naborforce/capabilities-pipelines
          path: naborforce/capabilities-pipelines
          token: ${{ github.TOKEN }}
          ref: main
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Increment Package Version
        uses: './naborforce/capabilities-pipelines/version-bump'
        with:
          package-file: 'package.json'
          search-files: '*.csproj'
          command: 'bump'
          
      - name: Build, Test, and Analyze
        uses: './naborforce/capabilities-pipelines/dotnet-build-test-analyze'
        with:
          path: 'Rosie.Nutshell.sln'
          sonar-project-key: 'nutshell-dotnet'
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Save Package Version
        uses: './naborforce/capabilities-pipelines/version-bump'
        with:
          git-tag-sources: true
          git-add-commit: true
          git-push-changes: true
          github-token: ${{ github.TOKEN }}

      - name: Push Packages to Nuget.org
        uses: "./naborforce/capabilities-pipelines/dotnet-nuget-push"
        with:
          nuget-source-name: 'nuget.org'
          nuget-source-token: ${{ secrets.NUGET_API_KEY }}