name: 'Build'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.get-version.outputs.version }}

    permissions:
      contents: write
      packages: write

    steps:
      - name: 'Download Source'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}