name: 'Build'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: 'Download Source'
        uses: actions/checkout@v3
        with:
          token: ${{ github.TOKEN }}

      - name: Checkout DevOps Capabilities Repo
        uses: actions/checkout@v3
        with:
          repository: naborforce/capabilities-pipelines
          path: naborforce/capabilities-pipelines
          token: ${{ github.TOKEN }}
          ref: main
          
      - name: Setup .NET SDK
        if: inputs.dotnet-version != ''
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
#
#      - name: Increment Package Version
#        uses: './naborforce/capabilities-pipelines/version-bump'
#        with:
#          package-file: 'package.json'
#          apply-files: |
#            src/Rosie.Nutshell/Rosie.Nutshell.csproj
#          command: 'bump'
#          nuget-source-user: ${{ secrets.USER }}
#          nuget-source-token: ${{ secrets.TOKEN }}
#          nuget-source-url: 'https://nuget.pkg.github.com/naborforce/index.json'
#
#      - name: Save Package Version
#        uses: './naborforce/capabilities-pipelines/version-bump'
#        with:
#          git-tag-sources: true
#          git-add-commit: true
#          git-push-changes: true
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build, Test, and Analyze
#        uses: './naborforce/capabilities-pipelines/dotnet-build'
#        with:
#          path: 'src/Rosie.Platform.sln'
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          token: ${{ secrets.TOKEN }}
#          sonar-project-key: 'enablement-platform'
#          sonar-token: ${{ secrets.SONAR_TOKEN }}
#
#      - name: Push Packages to Nuget.org
#        uses: "./naborforce/capabilities-pipelines/dotnet-nuget-push"
#        with:
#          nuget-source-name: 'nuget.org'
#          nuget-source-token: ${{ secrets.NUGET_API_KEY }}